### ISSUE TITLE
Dealing with duplicate map instances

### ISSUE THREAD

**Issue by danbramall** [stephenscaff/google-maps-es6#14]
Hi,

Thanks for a really useful bunch of code :)  I'm wondering what is the best way to implement this script in a scenario where there are multiple map instances on a page? My CMS outputs the HTML for the map and the accompanying JavaScript inline in the web page, so I could feasibly end up with something like this:

```
<div
      class="map__map js-map-1"
      data-lat="40.436821"
      data-lng="-79.908803"
      data-address="2005 Beechwood Blvd, Pittsburgh, PA 15217"
      data-title="Marker Title"
      data-zoom="14">
</div>
<script type="module">
  import * as Gmap from './GMap'
  Gmap.GMap('.js-map-1', 'MY_GOOGLE_MAPS_API_KEY_HERE')
</script>

<div
      class="map__map js-map-2"
      data-lat="40.436821"
      data-lng="-79.908803"
      data-address="2005 Beechwood Blvd, Pittsburgh, PA 15217"
      data-title="Marker Title"
      data-zoom="14">
</div>
<script type="module">
  import * as Gmap from './GMap'
  Gmap.GMap('.js-map-2', 'MY_GOOGLE_MAPS_API_KEY_HERE')
</script>
```

This results in a console warning: "You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors." and the maps don't render.

I was thinking I could create a global variable somewhere called 'mapsLoaded' and set this to true once the `load()` method promise resolves, then check the value of that variable inside that method in order to determine whether it should run or not.  I'm not sure if that's the best way though.  I was wondering how you'd suggest going about this?

Many thanks!

**Comment by stephenscaff** [comment]
Hey hey hey

So, I’ve never implemented it inside a script tag module like that. So, not
sure how to resolve with that approach off hand. But looks like your
basically initializing twice. You don’t need too.

Note, I went with the data attributes approach specifically to support
multiple maps on same page, generally from cms outputted data.

They way I’d do it is to simply include the map js in global js file
(presuming a vanilla js kind of project).

Since es6 you’ll need to use a transpiler set up still (ie: gulp + babel +
browserfy, or webpack, or even a super simple parcel.js setup)

Then, you can simply add maps with the data atta for lat lng. Basically,
the Google maps script includes their callback param, which calls the init
to render map.



The one gotcha is throwing errors pages without maps, so you need make sure
to check if your map element exists before you init. Unless you use your
cms to just load the transpires map js on pages with the maps.

Let me know if you need any examples specifically…. A good gulpfile sample,
etc.

Hope that helps?

Thanks.

**Comment by danbramall** [comment]
Thanks Stephen. I've got it to work on multiple map instances no problem, and am a big fan of using data attibutes for this kind of thing myself too, so all good in that respect. The issue really is just the specific way the CMS loads the modules, they're supposed to be entirely 'self-sufficient'. I could do away with that approach and split things up such that the map initialisation happened only once when there's at least one map on the page but the purist in me wanted to make it so that it didn't need to load any of the map JS at all outside of the individual map modules. There are a couple of ways I can perhaps go about this, but I wanted to check first if you could see a way of getting the JavaScript to know whether it had already loaded the Google Maps script or not, but it's a bit fiddly to accomplish that what with the Google Maps script being async and using the callback as it does.

I'll put my thinking cap on again.  Thanks again for getting back to me; appreciate it! :)
